spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:119.23.11.21:3306}/myblockchain?autoReconnect=true&useUnicode=true
    username: root
    password: ${MYSQL_PASS:123456}
server:
  port: 8080